### ISSUE TITLE
base de travail de peter troxler

### ISSUE THREAD

**Issue by clemclemmm** [daweeed/fabxml#1]
hoy !

tu as utiliser la base de travail qu'avait fait peter troxler y'a un moment, ou parti from scratch ?

**Comment by daweeed** [comment]
Salut, 

C'est en effet largement inspiré de son travail autour du fabml. 

Nous avions étudié cela lors du workshop à Ping l'an dernier : 
http://fablabo.net/wiki/WorkshopDocumentation/FabmlOntologies
